name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SSLMODE: ${{ secrets.DB_SSLMODE }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: DotNet Restore
      run: dotnet restore '**/*.csproj'

    - name: DotNet Build
      run: dotnet build '**/*.csproj' --configuration Release

    - name: DotNet Publish
      run: dotnet publish '**/*.csproj' --configuration Release --output ${{ github.workspace }}/api

    - name: Install EF Core CLI Tools
      run: dotnet tool install dotnet-ef --version 8.0.0 --global

    - name: Apply EF Core Migrations
      run: dotnet ef database update --project ${{ github.workspace }}/DealmateApi/DealmateApi.csproj --connection "Host=${{ env.DB_HOST }};Database=${{ env.DB_NAME }};Username=${{ env.DB_USER }};Password=${{ env.DB_PASSWORD }};SslMode=${{ env.DB_SSLMODE }}"

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install and Build UI
      run: |
        npm install
        npm run build
      working-directory: ui

    - name: Move UI Build to Drop Folder
      run: cp -r ui/build ${{ github.workspace }}/build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: drop
        path: ${{ github.workspace }}

    - name: Run Unit Tests
      run: dotnet test '**/DealmateUnitTest.csproj'
